# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(962, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 2, 1, 1)
        self.tiff_position_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab)
        self.tiff_position_doubleSpinBox.setMinimum(-9999.0)
        self.tiff_position_doubleSpinBox.setMaximum(9999.0)
        self.tiff_position_doubleSpinBox.setObjectName("tiff_position_doubleSpinBox")
        self.gridLayout_3.addWidget(self.tiff_position_doubleSpinBox, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 5, 1, 1)
        self.saveTiffROI = QtWidgets.QPushButton(self.tab)
        self.saveTiffROI.setObjectName("saveTiffROI")
        self.gridLayout_3.addWidget(self.saveTiffROI, 3, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 2, 1, 1)
        self.setTiffROItoBG = QtWidgets.QPushButton(self.tab)
        self.setTiffROItoBG.setObjectName("setTiffROItoBG")
        self.gridLayout_3.addWidget(self.setTiffROItoBG, 3, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem3, 0, 1, 1, 1)
        self.openWN = QtWidgets.QPushButton(self.tab)
        self.openWN.setObjectName("openWN")
        self.gridLayout_3.addWidget(self.openWN, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 3, 1, 1)
        self.openTiff = QtWidgets.QPushButton(self.tab)
        self.openTiff.setObjectName("openTiff")
        self.gridLayout_3.addWidget(self.openTiff, 1, 0, 1, 1)
        self.setTiffROItoCARS = QtWidgets.QPushButton(self.tab)
        self.setTiffROItoCARS.setObjectName("setTiffROItoCARS")
        self.gridLayout_3.addWidget(self.setTiffROItoCARS, 3, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 4, 1, 1)
        self.pglayout = QtWidgets.QGridLayout()
        self.pglayout.setObjectName("pglayout")
        self.gridLayout_3.addLayout(self.pglayout, 2, 0, 1, 6)
        self.image_info_label = QtWidgets.QLabel(self.tab)
        self.image_info_label.setObjectName("image_info_label")
        self.gridLayout_3.addWidget(self.image_info_label, 0, 5, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.singularValues_spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.singularValues_spinBox.setMinimum(1)
        self.singularValues_spinBox.setProperty("value", 10)
        self.singularValues_spinBox.setObjectName("singularValues_spinBox")
        self.gridLayout_2.addWidget(self.singularValues_spinBox, 0, 1, 1, 1)
        self.svdLayout = QtWidgets.QGridLayout()
        self.svdLayout.setObjectName("svdLayout")
        self.gridLayout_2.addLayout(self.svdLayout, 3, 0, 1, 7)
        self.singularValue_spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.singularValue_spinBox.setMinimum(-1)
        self.singularValue_spinBox.setProperty("value", -1)
        self.singularValue_spinBox.setObjectName("singularValue_spinBox")
        self.gridLayout_2.addWidget(self.singularValue_spinBox, 0, 3, 1, 1)
        self.setSVDValue = QtWidgets.QPushButton(self.tab_2)
        self.setSVDValue.setObjectName("setSVDValue")
        self.gridLayout_2.addWidget(self.setSVDValue, 1, 2, 1, 2)
        self.saveSVDROI = QtWidgets.QPushButton(self.tab_2)
        self.saveSVDROI.setObjectName("saveSVDROI")
        self.gridLayout_2.addWidget(self.saveSVDROI, 4, 6, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 4, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.setSVDROItoBG = QtWidgets.QPushButton(self.tab_2)
        self.setSVDROItoBG.setObjectName("setSVDROItoBG")
        self.gridLayout_2.addWidget(self.setSVDROItoBG, 4, 5, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 4, 1, 1)
        self.setSVDROItoCARS = QtWidgets.QPushButton(self.tab_2)
        self.setSVDROItoCARS.setObjectName("setSVDROItoCARS")
        self.gridLayout_2.addWidget(self.setSVDROItoCARS, 4, 4, 1, 1)
        self.saveSVD_all = QtWidgets.QPushButton(self.tab_2)
        self.saveSVD_all.setObjectName("saveSVD_all")
        self.gridLayout_2.addWidget(self.saveSVD_all, 0, 6, 1, 1)
        self.saveSVD = QtWidgets.QPushButton(self.tab_2)
        self.saveSVD.setObjectName("saveSVD")
        self.gridLayout_2.addWidget(self.saveSVD, 1, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.applySVD = QtWidgets.QPushButton(self.tab_2)
        self.applySVD.setObjectName("applySVD")
        self.gridLayout_2.addWidget(self.applySVD, 1, 0, 1, 2)
        self.svd_position_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.svd_position_doubleSpinBox.setMinimum(-9999.0)
        self.svd_position_doubleSpinBox.setMaximum(9999.0)
        self.svd_position_doubleSpinBox.setObjectName("svd_position_doubleSpinBox")
        self.gridLayout_2.addWidget(self.svd_position_doubleSpinBox, 4, 1, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.RamanRetrieval = QtWidgets.QWidget()
        self.RamanRetrieval.setObjectName("RamanRetrieval")
        self.gridLayout = QtWidgets.QGridLayout(self.RamanRetrieval)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.RamanRetrieval)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.RamanRetrieval)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 3, 1, 1)
        self.smoothness_spinbox = QtWidgets.QSpinBox(self.RamanRetrieval)
        self.smoothness_spinbox.setMaximum(10)
        self.smoothness_spinbox.setProperty("value", 5)
        self.smoothness_spinbox.setObjectName("smoothness_spinbox")
        self.gridLayout.addWidget(self.smoothness_spinbox, 1, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.RamanRetrieval)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 3, 1, 1)
        self.openCARSIntensity = QtWidgets.QPushButton(self.RamanRetrieval)
        self.openCARSIntensity.setObjectName("openCARSIntensity")
        self.gridLayout.addWidget(self.openCARSIntensity, 2, 0, 1, 1)
        self.openBackground = QtWidgets.QPushButton(self.RamanRetrieval)
        self.openBackground.setObjectName("openBackground")
        self.gridLayout.addWidget(self.openBackground, 1, 0, 1, 1)
        self.saveRetrieved = QtWidgets.QPushButton(self.RamanRetrieval)
        self.saveRetrieved.setObjectName("saveRetrieved")
        self.gridLayout.addWidget(self.saveRetrieved, 5, 5, 1, 1)
        self.savgol_window_retr_spinbox = QtWidgets.QSpinBox(self.RamanRetrieval)
        self.savgol_window_retr_spinbox.setMinimum(1)
        self.savgol_window_retr_spinbox.setMaximum(9999)
        self.savgol_window_retr_spinbox.setProperty("value", 101)
        self.savgol_window_retr_spinbox.setObjectName("savgol_window_retr_spinbox")
        self.gridLayout.addWidget(self.savgol_window_retr_spinbox, 3, 4, 1, 1)
        self.asymmetry_spinbox = QtWidgets.QSpinBox(self.RamanRetrieval)
        self.asymmetry_spinbox.setMinimum(-10)
        self.asymmetry_spinbox.setMaximum(-1)
        self.asymmetry_spinbox.setProperty("value", -4)
        self.asymmetry_spinbox.setObjectName("asymmetry_spinbox")
        self.gridLayout.addWidget(self.asymmetry_spinbox, 2, 4, 1, 1)
        self.ramanRetrievalLayout = QtWidgets.QGridLayout()
        self.ramanRetrievalLayout.setObjectName("ramanRetrievalLayout")
        self.gridLayout.addLayout(self.ramanRetrievalLayout, 4, 0, 1, 8)
        self.label_9 = QtWidgets.QLabel(self.RamanRetrieval)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 3, 1, 2)
        self.applyRetrieval = QtWidgets.QPushButton(self.RamanRetrieval)
        self.applyRetrieval.setObjectName("applyRetrieval")
        self.gridLayout.addWidget(self.applyRetrieval, 3, 0, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 2, 2, 1, 1)
        self.tabWidget.addTab(self.RamanRetrieval, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 962, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saveTiffROI.setText(_translate("MainWindow", "Save ROI"))
        self.setTiffROItoBG.setText(_translate("MainWindow", "Set ROI as background"))
        self.label_10.setText(_translate("MainWindow", "Current position"))
        self.openWN.setText(_translate("MainWindow", "Load Index Wavenumbers"))
        self.openTiff.setText(_translate("MainWindow", "Open TIFF"))
        self.setTiffROItoCARS.setText(_translate("MainWindow", "Set ROI as CARS"))
        self.image_info_label.setText(_translate("MainWindow", "No image loaded"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Raw Hyperspectra"))
        self.setSVDValue.setText(_translate("MainWindow", "Display singular value"))
        self.saveSVDROI.setText(_translate("MainWindow", "Save ROI"))
        self.label_11.setText(_translate("MainWindow", "Current position"))
        self.setSVDROItoBG.setText(_translate("MainWindow", "Set ROI as background"))
        self.setSVDROItoCARS.setText(_translate("MainWindow", "Set ROI as CARS"))
        self.saveSVD_all.setText(_translate("MainWindow", "Save All SVD"))
        self.saveSVD.setText(_translate("MainWindow", "Save SVD"))
        self.label_5.setText(_translate("MainWindow", "Singular value"))
        self.label_4.setText(_translate("MainWindow", "# of singular values"))
        self.applySVD.setText(_translate("MainWindow", "SVD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "SVD"))
        self.label.setText(_translate("MainWindow", "Smoothness "))
        self.label_3.setText(_translate("MainWindow", "Savitzky Golay Window"))
        self.label_2.setText(_translate("MainWindow", "Asymmetry"))
        self.openCARSIntensity.setText(_translate("MainWindow", "Load CARS"))
        self.openBackground.setText(_translate("MainWindow", "Load background"))
        self.saveRetrieved.setText(_translate("MainWindow", "Save retrieved"))
        self.label_9.setText(_translate("MainWindow", "Retrieval parameters"))
        self.applyRetrieval.setText(_translate("MainWindow", "Retrieve"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RamanRetrieval), _translate("MainWindow", "Raman Retrieval"))

